db:
  user: monetizeai_free_user
  password: mgstudio884
  host: 127.0.0.1
  port: 3306
  name: monetizeai_free_farsi

smsapikey: "OWYzZmNmNGYtZjEzMi00YjIyLWJhMzgtYmFjZjQ3NWFmMjIxMDcwZGE0ZWMwZDcyYzAxNjcxZDlkMjU0MzAzZmJhMGY="
from_number: "+983000505"
sms_base_url: "http://edge.ippanel.com/v1"

patterns:
  registration: "pattern_code_registration"
  followup1_3h: "pattern_code_followup1_3h"
  followup1_15h: "pattern_code_followup1_15h"
  followup2_3h: "pattern_code_followup2_3h"
  followup2_15h: "pattern_code_followup2_15h"
  followup3_3h: "pattern_code_followup3_3h"
  followup3_15h: "pattern_code_followup3_15h"
  followup4_3h: "pattern_code_followup4_3h"
  followup4_15h: "pattern_code_followup4_15h"
  complete1: "pattern_code_complete1"
  complete2: "pattern_code_complete2"
  complete3: "pattern_code_complete3"
  complete4: "pattern_code_complete4" 